### ISSUE TITLE
ModuleNotFoundError: No module named 'standard_cpp_systems'

### ISSUE THREAD

**Issue by yuqJin** [LeeLinJun/mpc-mpnet-py#6]
Hi, Thanks for your code!

I met a problem when generating the environment. It reported 
'ModuleNotFoundError: No module named 'standard_cpp_systems' '

I did not find the relevant issues, can you give me some clues?

**Comment by LeeLinJun** [comment]
Hi, thanks for your interest.

standard_cpp_systems module comes from CPP-python-bindings inside deps/ folder, and that part comes from the [sst python binding repository ](https://github.com/olegsinyavskiy/sparse_rrt), you can also check the repo for that part or [my own fork](https://github.com/LeeLinJun/sparse_rrt-1/tree/6dbd48539a7868e57d10e9989737d8a3692a2a52). 

Firstly please make sure the bindings have been correctly compiled.

If the module still can't be found, please make sure it has been correctly added to sys.path in data_gen/data_generation.py

**Comment by yuqJin** [comment]
Thank you for your reply!

Actually I compiled the bindings according to the following steps
- git clone https://github.com/pybind/pybind11    (to sparse_rrt-1/deps)
- mkdir build
- cd build
- cmake ..
- make check -j 4
- make install

And I have added the sys.path of sparse_rrt-1 to the data_gen/data_generation.py according to your code. But it still seems unable to work. Are there any other steps required for bindings?

**Comment by LeeLinJun** [comment]
If the bindings(for example, sparse_rrt/_sst_module.so contains all you need for standard_cpp_systems) are generated successfully, you don't need other steps. You can also check pybind11 documentation to correctly import the bindings.

If you can find your _sst_module.so and _mpc_mpnet_module.so inside deps/sparse-rrt-1/sparse_rrt folder, I would suggest trying to add sys.path and import sparse_rrt inside an interpreter to see if it can find the bindings, or running some tests inside sparse-rrt repo to see if it works.

**Comment by thisisjaskaran** [comment]
Hi

I was having the same issue. The pybindings are successfully building and I can see the  _sst_module.so and _mpc_mpnet_module.so files as well. I have also added the sparse_rrt path to my sys.path. However, I am still getting the following error on running `bash datagen_quadrotor_obs_batch1.sh`:-

```
Traceback (most recent call last):
  File "data_generation.py", line 8, in <module>
    from sparse_rrt.systems import standard_cpp_systems
  File "/home/jaskaran/.local/lib/python3.8/site-packages/sparse_rrt/systems/__init__.py", line 1, in <module>
    import standard_cpp_systems
ModuleNotFoundError: No module named 'standard_cpp_systems'
```
I also tried running it in a local interpreter as you recommended. This is what I got :-
```
>>> import sys
>>> sys.path.append('/home/jaskaran/mpc-mpnet-py/deps/sparse_rrt-1')
>>> from sparse_rrt.systems import standard_cpp_systems
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jaskaran/.local/lib/python3.8/site-packages/sparse_rrt/__init__.py", line 1, in <module>
    from _version import __version__
ModuleNotFoundError: No module named '_version'
```
Any ideas how I can fix it?

Thanks!

**Comment by thisisjaskaran** [comment]
Okay so I found the problem.

The issue arises when you have installed sparse_rrt via pip as well. Due to this, there is a prepend in the sys path with the location of that pip install.

```
File "/home/jaskaran/.local/lib/python3.8/site-packages/sparse_rrt/systems/__init__.py", line 1, in <module>
    import standard_cpp_systems
```
`.local/lib/python3.8/site-packages` in my case.

To sidestep this, you can replace the `sys.append` in data_generation.py with `sys.insert`

For instance, in my case :-
```
sys.path.append('/home/jaskaran/mpc-mpnet-py/deps/sparse_rrt-1')
```
becomes
```
sys.path.insert(0,'/home/jaskaran/mpc-mpnet-py/deps/sparse_rrt-1')
```
